### ISSUE TITLE
Plex don't give a fuck about autoscan :(

### ISSUE THREAD

**Issue by TheNexter** [Cloudbox/autoscan#112]
Plex, Sonarr and radarr : Docker linuxserver.io
Autoscan : docker hotio

My config 👍
```yaml
port: 3030

triggers:
  sonarr:
    - name: sonarr
      - from: /tv/
      to: /Plex/

  manual:
    rewrite:
    - from: /Google/
      to: /Plex/Google/
      
targets:
  plex:
    - url: http://192.168.0.28:32400
      token: *mytoken*
```     

My log 👍 

![image](https://user-images.githubusercontent.com/17613028/115131369-f325a080-9ff7-11eb-8d9a-3779eecdfa35.png)

When i stop the container autoscan, in plex log 👍 
![image](https://user-images.githubusercontent.com/17613028/115131240-d9d02480-9ff6-11eb-9a7c-0d1734e9f8de.png)

Anyone have a idea ? :(
