### ISSUE TITLE
Bind to specific network interfaces

### ISSUE THREAD

**Issue by agneevX** [Cloudbox/autoscan#125]
Currently, autoscan binds to all interfaces by default. 

Would be nice if it could bind to specified interfaces:

```yml
host: 127.0.0.1
host:
  - 127.0.0.1
  - 10.0.0.2
```
