### ISSUE TITLE
Multiple Paths for one trigger?

### ISSUE THREAD

**Issue by rycore** [Cloudbox/autoscan#129]
In Sonarr I have **path/AnimeTV**, **path/KidsTV** and **path/TV**, because I like to keep these things seperate, with Autoscan I don't see anything in the documentation about whether or not we can add multiple paths, we can add multiple triggers, but not paths. Also can we add an anchor to more than one mount if we're not using UnionFS or MergerFS? If I have AnimeTV in one mount and TV/KidsTV in another mount?

Here's an example of how i think I can write this, but would greatly appreciate any help.
```
anchors:
  - /mnt/fusemount/Gdrive-Series/anchor.txt
  - /mnt/fusemount/Gdrive-AnimeTV/anchor.txt
  - /mnt/fusemount/Gdrive-Movies/anchor.txt

triggers:
  sonarr:
    - name: sonarr-docker # /triggers/sonarr-docker
      priority: 2

      # Rewrite the path from within the container
      # to your local filesystem.
      rewrite:
        - from: /mnt/fusemount/Gdrive-Series/TV/
          to: /mnt/fusemount/Gdrive-Series/TV/

        - from: /mnt/fusemount/Gdrive-Series/KidsTV/
          to: /mnt/fusemount/Gdrive-Series/KidsTV/

        - from: /mnt/fusemount/Gdrive-AnimeTV/
          to: /mnt/fusemount/Gdrive-AnimeTV/
```

**Comment by edrock200** [comment]
Your thought is correct, but given that the paths are identical, you don't need any rewrite rules.

**Comment by rycore** [comment]
> 
> 
> Your thought is correct, but given that the paths are identical, you don't need any rewrite rules.

Thanks for letting me know I was on the right track. I assume then I just do the following.

```
anchors:
  - /mnt/fusemount/Gdrive-Series/anchor.txt
  - /mnt/fusemount/Gdrive-AnimeTV/anchor.txt
  - /mnt/fusemount/Gdrive-Movies/anchor.txt

triggers:
  sonarr:
    - name: sonarr-docker # /triggers/sonarr-docker
      priority: 2

      # Rewrite the path from within the container
      # to your local filesystem.
      paths:
        - path: /mnt/fusemount/Gdrive-Series/TV/
        - path: /mnt/fusemount/Gdrive-Series/KidsTV/
        - path: /mnt/fusemount/Gdrive-AnimeTV/
```

Or is it possible to just run path: `/mnt/fusemount/Gdrive-Series/` for both TV and KidsTV?

**Comment by m-rots** [comment]
```
anchors:
  - /mnt/fusemount/Gdrive-Series/anchor.txt
  - /mnt/fusemount/Gdrive-AnimeTV/anchor.txt
  - /mnt/fusemount/Gdrive-Movies/anchor.txt

triggers:
  sonarr:
    - name: sonarr-docker # /triggers/sonarr-docker
      priority: 2
```

As @edrock200 mentioned, you do not need any rewrite rules. So the above config is all you need for the sonarr trigger.

I assume the three paths are scannable by Plex directly and thus do not need to be converted. Otherwise I'd suggest you to read [the basics of path rewriting](https://github.com/Cloudbox/autoscan#rewriting-paths) first as it would be possible to rewrite `/mnt/fusemount/` to anything else.
