### ISSUE TITLE
Lidarr: failed determining libraries

### ISSUE THREAD

**Issue by hr1232** [Cloudbox/autoscan#144]
While Sonarr and Radarr triggers work perfectly, Lidarr triggers fail from time to time. The message I get is `failed determining libraries`. Doesn't seem to be a configuration issue, as most of the time it works.

As you can see, I am conforming to the default Plex naming scheme. Library path is `/mnt/google/Musik` in Plex, as well as in Lidarr, with no rewriting configured for the Lidarr trigger.

Because of the very basic logging with unclear messages I cannot be sure. I suspect, however, that the error turns up whenever Plex doesn't know the artist yet. Whenever a new album for a known artist is added, it seems to work fine. Might this have to do with directory structure being a bit different for music libraries compared to movie and tv libraries (additional sub-directory in `artist/album/file.mp3` as opposed to `movie/file.mp4` or `series/file.mp4`)?

Log:
```
Jan  6 21:00:45 INF Scan moved to processor event=Download method=POST path="/mnt/google/Musik/Eric Clapton/There’s One in Every Crowd (1975)" request_id=c7bkkrff2ncs6vpuqoj0 url=/triggers/lidarr
Jan  6 21:01:45 WRN No target libraries found error="/mnt/google/Musik/Eric Clapton/There’s One in Every Crowd (1975): failed determining libraries" target=plex url=http://plex.local
```

Config:
```
# <- triggers ->
port: 80
triggers:
  sonarr:
    - name: lidarr # /triggers/sonarr
      priority: 1
  radarr:
    - name: lidarr # /triggers/radarr
      priority: 1
  lidarr:
    - name: lidarr # /triggers/lidarr
      priority: 1
# <- processor ->
minimum-age: 5m
scan-delay: 5s
scan-stats: 1m
anchors:
  - /mnt/google/.mntchk
authentication:
  username: [*****]
  password: [*****]
# <- targets ->
targets:
  plex:
    - url: http://plex.local
      token: [*****]
```
