### ISSUE TITLE
No Target Libraries Found After Adding Second Path

### ISSUE THREAD

**Issue by hwwilliams** [Cloudbox/autoscan#147]
I'm in the process of moving some files for Plex across to another filesystem, I was trying to cause as little downtime for missing files in Plex as possible by mounting both the old and the new directory inside the Plex library but whenever Autoscan needs to process a scan request on the new path it says that no target libraries are found and I assume that means it failed to find a library in Plex with that new path but I do have libraries with the Path so I'm not sure what's going on.

I was looking for some clarification on whether Autoscan even supports sending scan requests to libraries with multiple paths or if this is a different issue as I don't understand what the error actually means.

The warning/error as shown in docker logs, the errors are coming from events triggered by Sonarr.

![image](https://user-images.githubusercontent.com/20447447/154864517-110d0f0d-e396-444d-a7ce-9d18cf01fb74.png)

These are the paths configured in Plex for the library I'm working with.

![image](https://user-images.githubusercontent.com/20447447/154864508-7336a819-ae0c-433d-955e-40aa55ceb174.png)

My config is shown below where I didn't need rewrites before because sonarr/radarr/plex/autoscan are all in docker containers that mount the data inside the same directories (i.e. Sonarr, Plex, and Autoscan containers all have `/data/tv` and `/mergerfs/tv` mounted inside them), this config was working perfectly prior to adding the `/mergerfs/tv`  paths. Autoscan still processes the `/data/tv` scan requests successfully during these failures which makes me think that Autoscan does work fine with Plex libraries that have multiple paths but I'm still not sure why it would say it found no target libraries.

```yaml                                                                                                                                                                                                                                                                        
anchors: [/data/movies/.movies.anchor, /data/tv/.tv.anchor, /mergerfs/tv/.tv.anchor]                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
triggers:                                                                                                                                                                                                                                                                                    
  inotify:                                                                                                                                                                                                                                                                                   
    - priority: 0                                                                                                                                                                                                                                                                            
      paths:                                                                                                                                                                                                                                                                                 
        - path: /data/movies/                                                                                                                                                                                                                                                                
        - path: /data/tv/                                                                                                                                                                                                                                                                    
        - path: /mergerfs/tv/                                                                                                                                                                                                                                                                
      include: []                                                                                                                                                                                                                                                                            
      exclude:                                                                                                                                                                                                                                                                               
        - '.Recycle.Bin/'                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                             
  radarr:                                                                                                                                                                                                                                                                                    
    - name: radarr                                                                                                                                                                                                                                                                           
      priority: 0                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                             
    - name: radarr-4k                                                                                                                                                                                                                                                                        
      priority: 1                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                             
  sonarr:                                                                                                                                                                                                                                                                                    
    - name: sonarr                                                                                                                                                                                                                                                                           
      priority: 0                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                             
    - name: sonarr-4k                                                                                                                                                                                                                                                                        
      priority: 1                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                             
targets:                                                                                                                                                                                                                                                                                     
  plex:                                                                                                                                                                                                                                                                                      
    - url: http://localhost:32400                                                                                                                                                                                                                                                            
      token: XXXXXXXXXXX
```

Any help would be appreciated.
