### ISSUE TITLE
 FTL Failed initialising target with HTTPS plex URL

### ISSUE THREAD

**Issue by mattsizzle** [Cloudbox/autoscan#216]
The following configuration results in an error currently.

`Aug 28 01:39:41 FTL Failed initialising target error="version: Get \"/\": unsupported protocol scheme \"\": target unavailable" target=plex target_url=`

```
targets:
  plex:
    - url: https://plex.example.com:32400
      token: .....
```

Please advise on the current syntax to use for a Plex server at an FQDN with a valid SSL certificate.
