### ISSUE TITLE
"ID does not exist from hook" error?

### ISSUE THREAD

**Issue by ImjuzCY** [Cloudbox/autoscan#57]
`Retryable error occurred while syncing drive error="XXXXXXXXXXXXX: performing partial sync: ID does not exist from hook: datastore: data anomaly" attempts=2 drive_id=XXXXXXXXXXXXX drive_name="Shared Drive" trigger=bernard`

I'm getting this error for bernard. What does that mean? 

config:
```
  bernard:
    - account: /config/app/sa.json
      cron: "*/5 * * * *" # every five minutes (the "" are important)
      drives:
        - id: XXXXXXXXXXXXX

      # rewrite drive to the local filesystem
      rewrite:
        - from: ^/unencrypted/
          to: /data/m/

      # filter with regular expressions
      include:
        - ^/data/m/tv-shows/
        - ^/data/m/movies/
      exclude:
        - '\.srt$'
```
