### ISSUE TITLE
Error i dont understanding 

### ISSUE THREAD

**Issue by stefan0028** [Cloudbox/autoscan#90]
i have this running on synology but im getting this in the log:
```
ERR Required fields are missing method=PUT request_id=c0k38u24qlig1jq0gc40 url=/triggers/sonarr
```

do i have to install somthing or add to the config ?

```
# <- processor ->

# override the minimum age to 30 minutes:
minimum-age: 30m

# set multiple anchor files

# <- triggers ->

# Optionally, protect your webhooks with authentication
authentication:
  username: 
  password: 

# port for Autoscan webhooks to listen on
port: 3030

triggers:
  sonarr:
    - name: sonarr # /triggers/sonarr
      priority: 2

  radarr:
    - name: radarr   # /triggers/radarr
      priority: 2
  lidarr:
    - name: lidarr   # /triggers/lidarr
      priority: 1

# <- targets ->

targets:
  plex:
```
